### ISSUE TITLE
Working on a fork of Agora.

### ISSUE THREAD

**Issue by halojoy** [Pecon/Agora#1]
As you can see I have forked Agora.
I have worked on improvements and small fixes for like a week now.

- Selectable **style** through modifying a variable in settings file,
- Made a **style_light.css** where is black color on lightgrey background.
- **Database rewrite**. Now any database can be chosen and installed. Uses PHP **PDO** drivers.
- Written new **CREATE TABLES** files for SQLite and MySQL.
- The CREATE TABLES part in setup now using separate files adapted for chosen database.
- I myself run Agora with the PDO SQLite database, selectable in setup.

Why dont you take a look at my FORK.
https://github.com/halojoy/Agora
I submit any changes as my work goes along.
It is of course in the Trunk. I do not plan any release. This is your job.
Finally I must say I like the Agora forum. I'm impressed by your work!
Hope people will use it.

**Comment by Pecon** [comment]
Heya, these sound like some great changes. Feel free to make a pull request, I'll be reviewing your changes for the next day or so.

**Comment by halojoy** [comment]
Okay.
I will do that.
If we merge my pull request, there is no real harm done,
because you always have your previous release 1.4 to go back to.
Why dont you release a small update 1.41 before,
just to save your recent work.

But I will take my time.
There have been a whole lot of issues only today.
Small fixes.
Nice for an old retired person to deal with. Born 1951.

I will only submit a pull request when I think the code is solid enough.
Thanks for your quick reply.

**Comment by halojoy** [comment]
I have added the 'issue' feature to my Agora.
There I will add new issues for things I change in Agora.
This way you can read about updates to the code.

I have for example labels: **fix, enchancement, bug, trouble, request**
Hope you will look into my issues.
Think this is best way for you to know what is going on and what is done to your script.
Regards.
https://github.com/halojoy/Agora
