### ISSUE TITLE
Agora tryout, error

### ISSUE THREAD

**Issue by halojoy** [Pecon/Agora#3]
Installation:  v2.0-beta1
First step is okay.  Database config.
Second step gives following error:
"Missing server config: theme"

So I stopped there.

**Comment by Pecon** [comment]
Hi. That issue is currently fixed in the repo but hasn't been tagged under a release yet. You can either just download the repo and use the current files as an install which should work fine, or you can edit the /data/.settings.json file to add `,"theme": "twilight"` to the json data there.

**Comment by halojoy** [comment]
Thanks.
So it will also be fixed in coming  releases.
I will try with using the master trunk.
